### ISSUE TITLE
Unable to build SDL when running library.sh on windows WSL

### ISSUE THREAD

**Issue by initram** [craftworkgames/Ankura#107]
I have tried to build the latest version of Katabasis from source, as it seems like an interesting project, but I get the following error when it starts to build SDL:

```
>bash library.sh
Target build operating system: 'microsoft' (default)
Target build CPU architecture: 'x86_64' (default)
Building SDL from source...
Started '/mnt/d/Repos/katabasis/ext/sdl-cs/library.sh' microsoft x86_64
Target build operating system: 'microsoft' (override)
Target build CPU architecture: 'x86_64' (override)
Building SDL...
CMake Error: The source directory "/mnt/d/Repos/katabasis/ext/sdl-cs/cmake-build-release" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Error: /mnt/d/Repos/katabasis/ext/sdl-cs/cmake-build-release is not a directory
The file '/mnt/d/Repos/katabasis/ext/sdl-cs/cmake-build-release/SDL2.dll' does not exist!
mv: cannot stat '/mnt/d/Repos/katabasis/ext/sdl-cs/lib/*': No such file or directory
Building SDL from source finished!
```

Am I missing some dependency or something? I have installed `cmake`, `unzip`, and `build-essential` in WSL, but I am not sure if I need more packages to build from WSL.

**Comment by lithiumtoast** [comment]
Hey @initram

I have recently discovered that WSL is not required and have not updated Katabasis scripts with that information. Moving forward running `.sh` scripts will be done using Git Bash which is available on Windows by installing Git. I'll update it soon.

**Comment by initram** [comment]
Please also list any other dependencies that need to be installed, like CMake, if I still have to install that (in windows this time). Looking forward to experimenting with Katabasis.

**Comment by initram** [comment]
I still get the same error when running the script from git bash, so I must be missing something.

**Comment by lithiumtoast** [comment]
Right, something has changed. I have recently updated SDL-cs and have it working on it's own: https://github.com/bottlenoselabs/SDL-cs. Katabasis would need to pull the submodule, but I need to update all the submodules at once related to SDL such as FNA3D.

**Comment by lithiumtoast** [comment]
Hey @initram, I updated all the scripts and tested on Windows, macOS, and Linux. Let me know if anything doesn't work for you.
