### ISSUE TITLE
FILE* throwing an error in imgui.cs

### ISSUE THREAD

**Issue by dinkumdingo** [craftworkgames/Ankura#99]
So I followed the steps in `BUILDING-FROM-SOURCE.md` and try to build but then I get these two errors at every occurrence of `'FILE*'`:
```
CS0246	The type or namespace name 'FILE' could not be found (are you missing a using directive or an assembly reference?)	Katabasis.Native	\katabasis\ext\imgui-cs\src\cs\production\imgui-cs\imgui.cs	9746	Active
CS0208	Cannot take the address of, get the size of, or declare a pointer to a managed type ('FILE')				Katabasis.Native	\katabasis\ext\imgui-cs\src\cs\production\imgui-cs\imgui.cs	9746	Active
```
I think C2CS is missing a C# equivalent of the FILE type to use in `imgui.cs`.

**Comment by lithiumtoast** [comment]
Hey @TRSpaceChicken, thanks for pointing this out.

I'm re-working C2CS as we speak this week. I'll fix it ASAP.
